# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "s"
controleur = "controleurs/schema.py"
template = "schema.html"

[[routes]]
url = "t"
controleur = "controleurs/table.py"
template = "table.html"

[[routes]]
url = "query"
controleur = "controleurs/query.py"
template = "requete.html"

[[routes]]
url = "logout"
controleur = "controleurs/logout.py"
template = "deconnexion.html"