# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "initialisation"
controleur = "controleurs/initialisation.py"
template = "initialisation.html"

[[routes]]
url = "jouer"
controleur = "controleurs/partie.py"
template = "partie.html"


#[[routes]]
#url = "ajouter"
#controleur = "controleurs/ajouter.py"
#template = "ajouter.html"

#[[routes]]
#url = "critiquer"
#controleur = "controleurs/critiques.py"
#template = "critiquer.html"
