# Définition d'un tableau de routes au format TOML (https://toml.io/)
# - url : chemin dans l'URL
# - controleur : chemin vers le fichier du controleur
# - template : chemin vers le fichier de template

[[routes]]
url = ""
controleur = "controleurs/accueil.py"
template = "accueil.html"

[[routes]]
url = "grille"
controleur = "controleurs/grille.py"
template = "grille.html"

[[routes]]
url = "generate"
controleur = "controleurs/grille.py"
template = "grille_base.html"

#[[routes]]
#url = "historique"
#controleur = "controleurs/historique.py"
#template = "historique.html"

#[[routes]]
#url = "ajouter"
#controleur = "controleurs/ajouter.py"
#template = "ajouter.html"

#[[routes]]
#url = "critiquer"
#controleur = "controleurs/critiques.py"
#template = "critiquer.html"
